---
dr_namespace: "boutique"
bubble_namespace: "boutique-bubble"
bubble_backup_name: "boutique-bubble-backup"
bubble_restore_name: "boutique-bubble-restore"
bubble_backup_location_name: "bubble-backup-location"
s3_bucket_prefix: "portworx-bubble-backups"
s3_region: "us-east-2"
