---
dr_namespace: "boutique"
bubble_namespace: "boutique-bubble"
bubble_clone_name: "boutique-bubble-clone"
portworx_namespace: "portworx"
stork_pod_label: "name=stork"
stork_binary_path: "/storkctl/linux/storkctl"
stork_clone_role_name: "stork-bubble-test-clone"
stork_clone_cluster_rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["create", "get", "list", "watch"]
stork_clone_namespace_rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
