portworx_namespace: "portworx"
stork_pod_label: "name=stork"
stork_binary_path: "/storkctl/linux/storkctl"
bubble_namespace: "boutique-bubble"
bubble_migration_name: "boutique-bubble-test"
cluster_pair_name: "boutique-cluster-pair"
dr_namespace: "boutique"
