---
- name: Get AWS Region from worker node
  ansible.builtin.set_fact:
    aws_region: "{{ worker_node.metadata.labels['topology.kubernetes.io/region'] }}"

- name: Extract EC2 instance ID from worker node
  ansible.builtin.set_fact:
    ec2_instance_id: "{{ worker_node.spec.providerID.split('/')[-1] }}"

- name: Get EC2 instance details
  amazon.aws.ec2_instance_info:
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
    instance_ids:
      - "{{ ec2_instance_id }}"
  register: ec2_instance

- name: Get security group for this cluster's worker nodes
  amazon.aws.ec2_security_group_info:
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
    filters:
      group-id: "{{ ec2_instance.instances[0].security_groups | map(attribute='group_id') | list }}"
      "tag:sigs.k8s.io/cluster-api-provider-aws/role": node
  register: aws_security_groups

- name: Assert that there is only one security group for the worker nodes
  ansible.builtin.assert:
    that:
      - aws_security_groups is defined
      - aws_security_groups.security_groups is defined
      - aws_security_groups.security_groups | length == 1
    fail_msg: >-
      Expected exactly one security group with the tag 'tag:sigs.k8s.io/cluster-api-provider-aws/role: node' but
      found {{ aws_security_groups.security_groups | length }}

- name: Set facts for worker node security group
  ansible.builtin.set_fact:
    aws_sg_id: "{{ aws_security_groups.security_groups[0].group_id }}"
    aws_sg_name: "{{ aws_security_groups.security_groups[0].group_name }}"
    aws_sg_vpc_id: "{{ aws_security_groups.security_groups[0].vpc_id }}"

- name: Add AWS Security Group ingress rules
  amazon.aws.ec2_security_group:
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    aws_region: "{{ aws_region }}"
    name: "{{ aws_sg_name }}"
    description: "Security groups for Portworx"
    vpc_id: "{{ aws_sg_vpc_id }}"
    purge_rules: false
    rules:
      - group_id: "{{ aws_sg_id }}"
        ports: "{{ sg_ports.tcp }}"
        proto: tcp
        rule_desc: "Portworx [tcp]"
      - group_id: "{{ aws_sg_id }}"
        ports: "{{ sg_ports.udp }}"
        proto: udp
        rule_desc: "Portworx [udp]"
