---
- name: Get worker nodes
  register: worker_nodes
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig }}"
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/worker"

- name: Assert there are worker nodes
  ansible.builtin.assert:
    that:
      - worker_nodes is defined
      - worker_nodes | length > 0
    fail_msg: There are no worker nodes present in the cluster with the given kubeconfig

- name: Apply ingress rules to all worker nodes
  ansible.builtin.include_tasks: add-ingress-rules-for-node.yml
  vars:
    worker_node: "{{ worker_nodes[0] }}"
