---
- name: Run Portworx DR Bubble Test
  hosts: localhost
  connection: local

  vars:
    secondary_kubeconfig: ""
    bubble_namespace: "boutique-bubble"
    cluster_pair_name: "boutique-cluster-pair"
    portworx_namespace: "portworx"
    dr_namespace: "boutique"

  tasks:
    - name: Run bubble test migration
      ansible.builtin.import_role:
        name: bubble-test
      vars:
        kubeconfig: "{{ secondary_kubeconfig }}"
