---
- name: Run Portworx DR Bubble Test
  hosts: localhost
  connection: local

  vars:
    secondary_kubeconfig: ""
    bubble_namespace: "boutique-bubble"
    cluster_pair_name: "boutique-cluster-pair"

  tasks:
    - name: Run bubble test migration
      ansible.builtin.import_role:
        name: bubble-test
      vars:
        kubeconfig: "{{ secondary_kubeconfig }}"
        cluster_pair_name: "{{ cluster_pair_name }}"
        bubble_namespace: "{{ bubble_namespace }}"
