---
- name: Tear Down Portworx DR Bubble Test
  hosts: localhost
  connection: local

  vars:
    secondary_kubeconfig: ""
    aws_access_key_id: ""
    aws_secret_access_key: ""

  tasks:
    - name: Tear down bubble test environment
      ansible.builtin.include_role:
        name: bubble-test-teardown
      vars:
        kubeconfig: "{{ secondary_kubeconfig }}"
