---
- name: Configure AWS for Portworx
  hosts: localhost
  connection: local
  vars:
    aws_access_key_id: "{{ aws_access_key_id }}"
    aws_secret_access_key: "{{ aws_secret_access_key }}"
    primary_kubeconfig: "{{ primary_kubeconfig }}"
    secondary_kubeconfig: "{{ secondary_kubeconfig }}"

  tasks:
    - name: Configure AWS for primary cluster
      ansible.builtin.include_role:
        name: configure-aws-portworx
      vars:
        kubeconfig: "{{ primary_kubeconfig }}"

    - name: Configure AWS for secondary cluster
      ansible.builtin.include_role:
        name: configure-aws-portworx
      vars:
        kubeconfig: "{{ secondary_kubeconfig }}"
