---
- name: Create Migration Schedule
  hosts: localhost
  connection: local

  vars:
    primary_kubeconfig: ""

  tasks:
    - name: Create migration schedule
      ansible.builtin.include_role:
        name: create-migration-schedule
      vars:
        kubeconfig: "{{ primary_kubeconfig }}"
