---
- name: Create Cluster Pair for Portworx
  hosts: localhost
  connection: local

  vars:
    primary_kubeconfig: ""
    secondary_kubeconfig: ""
    aws_access_key_id: ""
    aws_secret_access_key: ""
    s3_region: "us-east-2"
    s3_endpoint: "minio-api-minio.apps.pwx-primary-1.aws.validatedpatterns.io"
    portworx_namespace: "portworx"
    cluster_pair_name: "boutique-cluster-pair"
    target_namespace: "boutique"

  tasks:
    - name: Create admin cluster pair
      ansible.builtin.include_role:
        name: create-cluster-pair
