---
- name: Create Migration
  hosts: localhost
  connection: local

  vars:
    primary_kubeconfig: ""
    portworx_namespace: "portworx"
    dr_namespace: "boutique"
    migration_name: "boutique-migration"
    use_admin_cluster_pair: "yes"
    cluster_pair: "admin-cluster-pair"

  tasks:
    - name: Create migration
      ansible.builtin.include_role:
        name: create-migration
      vars:
        kubeconfig: "{{ primary_kubeconfig }}"
        admin_cluster_pair: "{{ cluster_pair if use_admin_cluster_pair | bool else '' }}"
        cluster_pair: "{{ '' if use_admin_cluster_pair | bool else cluster_pair }}"
